// <auto-generated />
using AutoShop1.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoShop1.Migrations.Shop
{
    [DbContext(typeof(ShopContext))]
    [Migration("20220319141642_change4")]
    partial class change4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoShop1.Data.Models.Shop", b =>
                {
                    b.Property<string>("nameShop")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdShop")
                        .HasColumnName("id_shop");

                    b.Property<string>("cityShop")
                        .HasColumnName("city_shop")
                        .HasMaxLength(50);

                    b.HasKey("nameShop");

                    b.ToTable("name_shop");
                });
#pragma warning restore 612, 618
        }
    }
}
